baseURL: "https://samsam779.github.io/myWeb/" 
title: Min-Hsin(Sam) Liu
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 2
        - name: Projects
          url: projects/
          weight: 3
        - name: Résumé
          url: resume.pdf
          weight: 4
        - name: My Fun Side
          url: funme
          weight: 5


params:
    description: "This website hosts Min-Hsin's research papers, projects, curriculum vitae, and contact information."
    author: Min-Hsin, Liu
    googleAnalyticsID: "G-0WCBVMZWLL"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["projects","papers","funme"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Min-Hsin(Sam) Liu
          subtitle: "--------------------------------------------------------------------------------\n\n
                  Hi! Welcome to my page!\n\n
                  I am an Electrical and Computer Engineering (ECE) MS student at the Georgia Institute of Technology and expected to graduate in December 2027. My research interests include digital IC design and integrated circuit(IC) testing.\n\n
                  I am currently seeking 2027 summer internship opportunities in the field of digital IC design, design for testability, or other related areas.\n\n
                  If you’d like to know more about me or my work, feel free to reach out!\n\n
                  --------------------------------------------------------------------------------\n\n
                  ## NEWS ##\n\n
                  1. Awarded the IEEE Taipei Section 2025 Best Master’s Thesis Award\n\n
                  2. Paper accepted by 2025 International Test Conference (ITC)\n\n
                  3. Paper accepted by 2025 VLSI Test Symposium (VTS)"
                  
          imageUrl: "face.png"
          imageWidth: 200
          imageHeight: 200
          buttons:
            - name: Papers
              url: papers/
            - name: Projects
              url: projects/
            - name: Résumé
              url: resume.pdf
            - name: My Fun Side
              url: funme/

    socialIcons:
        - name: Email
          url: mailto:sam20000927@gmail.com
        - name: GitHub
          url: https://github.com/samsam779
        - name: LinkedIn
          url: https://linkedin.com/in/minhsinliu




    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Min-Hsin(Sam) Liu"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2